const p = (id) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=480&h=600&fit=crop`;

const mockProducts = [
  // ── MEN'S SHIRTS ──
  {
    _id: "mock_001",
    name: "Classic White Oxford Shirt",
    brand: "Raymond",
    price: 1299, mrp: 2499, discount: 48,
    category: "Men", subCategory: "Shirts", gender: "Men",
    description: "Premium 100% cotton Oxford shirt. Perfect for office and casual outings. Wrinkle-resistant slim fit.",
    image: p(901424), image2: p(708440),
    rating: 4.5, reviewCount: 2341,
    sizes: ["S","M","L","XL","XXL"], colors: ["#FFFFFF","#87CEEB","#F5F5DC"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_002",
    name: "Navy Blue Linen Shirt",
    brand: "Zara",
    price: 1899, mrp: 3499, discount: 46,
    category: "Men", subCategory: "Shirts", gender: "Men",
    description: "Breathable linen shirt perfect for summer. Semi-casual fit with button-down collar.",
    image: p(1043471), image2: p(19305993),
    rating: 4.4, reviewCount: 1892,
    sizes: ["S","M","L","XL","XXL"], colors: ["#1e3a5f","#FFFFFF","#6b7280"],
    inStock: true, freeShipping: true,
  },
  {
    _id: "mock_003",
    name: "Flannel Check Shirt",
    brand: "H&M",
    price: 999, mrp: 1799, discount: 44,
    category: "Men", subCategory: "Shirts", gender: "Men",
    description: "Classic flannel check shirt in soft brushed cotton. A wardrobe essential for casual weekends.",
    image: p(3036513), image2: p(1212100),
    rating: 4.3, reviewCount: 3210,
    sizes: ["S","M","L","XL","XXL"], colors: ["#dc2626","#1e3a5f","#374151"],
    inStock: true, isSale: true, freeShipping: true,
  },
  {
    _id: "mock_004",
    name: "Piqué Polo Shirt",
    brand: "Lacoste",
    price: 2499, mrp: 4499, discount: 44,
    category: "Men", subCategory: "Shirts", gender: "Men",
    description: "Iconic piqué cotton polo with ribbed collar and cuffs. A timeless classic.",
    image: p(614810), image2: p(34976),
    rating: 4.7, reviewCount: 5421,
    sizes: ["S","M","L","XL","XXL","3XL"], colors: ["#FFFFFF","#1e3a5f","#dc2626","#374151"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_005",
    name: "Denim Shirt for Men",
    brand: "Levis",
    price: 1499, mrp: 2799, discount: 46,
    category: "Men", subCategory: "Shirts", gender: "Men",
    description: "Classic western-style denim shirt with two chest pockets and snap buttons.",
    image: p(10004175), image2: p(1212100),
    rating: 4.5, reviewCount: 3344,
    sizes: ["S","M","L","XL","XXL"], colors: ["#1e3a5f","#6b7280"],
    inStock: true, freeShipping: true,
  },

  // ── MEN'S T-SHIRTS ──
  {
    _id: "mock_006",
    name: "Men's Graphic Oversized Tee",
    brand: "H&M",
    price: 699, mrp: 1299, discount: 46,
    category: "Men", subCategory: "T-Shirts", gender: "Men",
    description: "Trendy oversized graphic tee in soft jersey cotton. The perfect streetwear staple.",
    image: p(14428678), image2: p(175657),
    rating: 4.3, reviewCount: 1876,
    sizes: ["S","M","L","XL","2XL"], colors: ["#000000","#FFFFFF","#4B5563"],
    inStock: true, isSale: true, freeShipping: true,
  },
  {
    _id: "mock_007",
    name: "Plain Round Neck T-Shirt",
    brand: "UCB",
    price: 499, mrp: 999, discount: 50,
    category: "Men", subCategory: "T-Shirts", gender: "Men",
    description: "Everyday essential plain round-neck tee in super-soft 100% combed cotton.",
    image: p(9775884), image2: p(8498700),
    rating: 4.2, reviewCount: 9876,
    sizes: ["S","M","L","XL","XXL","3XL"], colors: ["#FFFFFF","#000000","#dc2626","#1e3a5f","#059669"],
    inStock: true, freeShipping: true,
  },
  {
    _id: "mock_008",
    name: "Nike Dri-FIT Training T-Shirt",
    brand: "Nike",
    price: 1499, mrp: 2799, discount: 46,
    category: "Men", subCategory: "T-Shirts", gender: "Men",
    description: "High-performance Dri-FIT training tee with sweat-wicking technology.",
    image: p(7658459), image2: p(175657),
    rating: 4.6, reviewCount: 5432,
    sizes: ["S","M","L","XL","XXL"], colors: ["#000000","#dc2626","#FFFFFF","#1e3a5f"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── MEN'S JEANS ──
  {
    _id: "mock_009",
    name: "Slim Fit Mid-Rise Blue Jeans",
    brand: "Levis 511",
    price: 1899, mrp: 3499, discount: 46,
    category: "Men", subCategory: "Jeans", gender: "Men",
    description: "Classic 511 slim-fit jeans with 2% stretch for all-day comfort.",
    image: p(6764007), image2: p(1082529),
    rating: 4.7, reviewCount: 5812,
    sizes: ["28","30","32","34","36","38"], colors: ["#1e3a5f","#374151"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_010",
    name: "Jet Black Skinny Jeans",
    brand: "Spykar",
    price: 1599, mrp: 2999, discount: 47,
    category: "Men", subCategory: "Jeans", gender: "Men",
    description: "Super-stretch skinny jeans in rich jet black with an edgy coated finish.",
    image: p(3908081), image2: p(4066292),
    rating: 4.5, reviewCount: 3121,
    sizes: ["28","30","32","34","36"], colors: ["#000000","#1c1c1c"],
    inStock: true, freeShipping: true,
  },
  {
    _id: "mock_011",
    name: "Tapered Fit Grey Jeans",
    brand: "Pepe Jeans",
    price: 1799, mrp: 3299, discount: 45,
    category: "Men", subCategory: "Jeans", gender: "Men",
    description: "Stylish tapered-leg grey jeans in stretch denim. Works with sneakers or boots.",
    image: p(1040496), image2: p(2272244),
    rating: 4.3, reviewCount: 1654,
    sizes: ["28","30","32","34","36"], colors: ["#6b7280","#374151"],
    inStock: true, isSale: true, freeShipping: true,
  },

  // ── WOMEN'S JEANS ──
  {
    _id: "mock_012",
    name: "Women's High-Waist Skinny Jeans",
    brand: "H&M",
    price: 1699, mrp: 2999, discount: 43,
    category: "Women", subCategory: "Jeans", gender: "Women",
    description: "Flattering high-rise skinny jeans with sculpting waistband and 4-way stretch.",
    image: p(1138560), image2: p(928008),
    rating: 4.6, reviewCount: 7234,
    sizes: ["24","26","28","30","32","34"], colors: ["#1e3a5f","#000000","#D4A574"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_013",
    name: "Wide Leg Flare Jeans",
    brand: "Zara",
    price: 2499, mrp: 4499, discount: 44,
    category: "Women", subCategory: "Jeans", gender: "Women",
    description: "70s-inspired wide-leg flare jeans with a high rise. Retro-chic silhouette.",
    image: p(5714510), image2: p(1138560),
    rating: 4.5, reviewCount: 3456,
    sizes: ["24","26","28","30","32"], colors: ["#1e3a5f","#000000"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── WOMEN'S TOPS ──
  {
    _id: "mock_014",
    name: "Women's Black Sleeveless Top",
    brand: "Zara",
    price: 799, mrp: 1499, discount: 47,
    category: "Women", subCategory: "Tops", gender: "Women",
    description: "Minimalist sleeveless top perfect for layering or wearing on its own.",
    image: p(2467394), image2: p(1055859),
    rating: 4.4, reviewCount: 2890,
    sizes: ["XS","S","M","L","XL"], colors: ["#000000","#FFFFFF","#374151"],
    inStock: true, freeShipping: true,
  },
  {
    _id: "mock_015",
    name: "Women's White Linen Top",
    brand: "Fabindia",
    price: 999, mrp: 1799, discount: 44,
    category: "Women", subCategory: "Tops", gender: "Women",
    description: "Breezy white linen button-down top. A sustainable everyday wardrobe essential.",
    image: p(852793), image2: p(2962121),
    rating: 4.4, reviewCount: 2234,
    sizes: ["XS","S","M","L","XL"], colors: ["#FFFFFF","#D4A574","#6b7280"],
    inStock: true, freeShipping: true,
  },

  // ── WOMEN'S DRESSES ──
  {
    _id: "mock_016",
    name: "Floral Wrap Midi Dress",
    brand: "Zara",
    price: 1999, mrp: 3499, discount: 43,
    category: "Women", subCategory: "Dresses", gender: "Women",
    description: "Elegant floral print wrap dress with tie waist. Flattering on all body types.",
    image: p(3517286), image2: p(1865726),
    rating: 4.6, reviewCount: 4512,
    sizes: ["XS","S","M","L","XL"], colors: ["#f472b6","#fbbf24","#34d399"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_017",
    name: "Red Maxi Evening Dress",
    brand: "FabAlley",
    price: 2299, mrp: 3999, discount: 43,
    category: "Women", subCategory: "Dresses", gender: "Women",
    description: "Stunning red maxi dress for special occasions. Flowy fabric with elegant drape.",
    image: p(5044409), image2: p(206349),
    rating: 4.5, reviewCount: 876,
    sizes: ["XS","S","M","L"], colors: ["#dc2626","#000000","#ec4899"],
    inStock: true, isSale: true, freeShipping: true,
  },
  {
    _id: "mock_018",
    name: "Women's Classic Black Dress",
    brand: "Mango",
    price: 1799, mrp: 3299, discount: 45,
    category: "Women", subCategory: "Dresses", gender: "Women",
    description: "Timeless little black dress. Bodycon fit, perfect for evenings out.",
    image: p(732496), image2: p(157961),
    rating: 4.7, reviewCount: 3120,
    sizes: ["XS","S","M","L","XL"], colors: ["#000000"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── WOMEN'S ETHNIC ──
  {
    _id: "mock_019",
    name: "Ethnic Printed Kurti",
    brand: "Biba",
    price: 1299, mrp: 2199, discount: 41,
    category: "Women", subCategory: "Ethnic", gender: "Women",
    description: "Beautiful block-printed A-line kurti in soft rayon. Ideal for festive occasions.",
    image: p(5595710), image2: p(28867973),
    rating: 4.5, reviewCount: 3678,
    sizes: ["S","M","L","XL","XXL"], colors: ["#7c3aed","#dc2626","#059669"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_020",
    name: "Lehenga Choli Set",
    brand: "Aurelia",
    price: 3999, mrp: 6999, discount: 43,
    category: "Women", subCategory: "Ethnic", gender: "Women",
    description: "Stunning lehenga choli with intricate embroidery. Perfect for weddings and festivals.",
    image: p(8881954), image2: p(27212065),
    rating: 4.8, reviewCount: 1234,
    sizes: ["S","M","L","XL"], colors: ["#dc2626","#fbbf24","#7c3aed","#ec4899"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_021",
    name: "Anarkali Salwar Suit",
    brand: "Biba",
    price: 2499, mrp: 4499, discount: 44,
    category: "Women", subCategory: "Ethnic", gender: "Women",
    description: "Graceful Anarkali salwar suit with dupatta. Flared floor-length silhouette.",
    image: p(11366734), image2: p(1149962),
    rating: 4.7, reviewCount: 1987,
    sizes: ["S","M","L","XL","XXL"], colors: ["#7c3aed","#dc2626","#059669","#fbbf24"],
    inStock: true, freeShipping: true,
  },

  // ── MEN'S JACKETS ──
  {
    _id: "mock_022",
    name: "Premium Leather Biker Jacket",
    brand: "Zara",
    price: 5999, mrp: 9999, discount: 40,
    category: "Men", subCategory: "Jackets", gender: "Men",
    description: "Genuine leather biker jacket with asymmetric zip. A timeless wardrobe investment.",
    image: p(2766298), image2: p(14882595),
    rating: 4.8, reviewCount: 932,
    sizes: ["S","M","L","XL"], colors: ["#1a1a1a","#4b2e1e"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_023",
    name: "Denim Trucker Jacket",
    brand: "Levis",
    price: 2499, mrp: 4499, discount: 44,
    category: "Men", subCategory: "Jackets", gender: "Men",
    description: "Classic Levis Trucker jacket in rigid denim. An enduring icon.",
    image: p(1040880), image2: p(2815417),
    rating: 4.7, reviewCount: 4321,
    sizes: ["S","M","L","XL","XXL"], colors: ["#1e3a5f","#6b7280","#374151"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_024",
    name: "Women's Power Suit Blazer",
    brand: "Mango",
    price: 3999, mrp: 6999, discount: 43,
    category: "Women", subCategory: "Jackets", gender: "Women",
    description: "Bold oversized blazer for a powerful modern look. Wear with trousers or over a dress.",
    image: p(2422293), image2: p(7615255),
    rating: 4.6, reviewCount: 1234,
    sizes: ["XS","S","M","L","XL"], colors: ["#1a1a1a","#374151","#FFFFFF"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── HOODIES ──
  {
    _id: "mock_025",
    name: "Cozy Fleece Hoodie",
    brand: "Nike",
    price: 2499, mrp: 4499, discount: 44,
    category: "Men", subCategory: "Hoodies", gender: "Men",
    description: "Ultra-soft fleece hoodie with kangaroo pocket and ribbed cuffs.",
    image: p(9920768), image2: p(15964553),
    rating: 4.6, reviewCount: 3204,
    sizes: ["S","M","L","XL","XXL"], colors: ["#374151","#1e3a5f","#7c3aed"],
    inStock: true, freeShipping: true,
  },
  {
    _id: "mock_026",
    name: "Women's Oversized Hoodie",
    brand: "H&M",
    price: 1799, mrp: 3299, discount: 45,
    category: "Women", subCategory: "Hoodies", gender: "Women",
    description: "Cosy oversized hoodie in soft brushed jersey. Perfect relaxed weekend vibes.",
    image: p(6763595), image2: p(6311486),
    rating: 4.5, reviewCount: 3456,
    sizes: ["XS","S","M","L","XL"], colors: ["#f9a8d4","#c4b5fd","#374151","#FFFFFF"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── SWEATERS ──
  {
    _id: "mock_027",
    name: "Men's Cable Knit Sweater",
    brand: "Marks & Spencer",
    price: 2299, mrp: 3999, discount: 43,
    category: "Men", subCategory: "Sweaters", gender: "Men",
    description: "Classic cable-knit crewneck sweater in 100% lambswool. A timeless winter essential.",
    image: p(7109087), image2: p(4047814),
    rating: 4.6, reviewCount: 1987,
    sizes: ["S","M","L","XL","XXL"], colors: ["#D4A574","#374151","#FFFFFF","#1e3a5f"],
    inStock: true, isTrending: true, freeShipping: true,
  },
  {
    _id: "mock_028",
    name: "Women's Chunky Knit Sweater",
    brand: "Mango",
    price: 2499, mrp: 4499, discount: 44,
    category: "Women", subCategory: "Sweaters", gender: "Women",
    description: "Trendy oversized chunky-knit sweater with dropped shoulders. Super cosy.",
    image: p(11446773), image2: p(4421760),
    rating: 4.6, reviewCount: 2109,
    sizes: ["XS","S","M","L","XL"], colors: ["#D4A574","#FFFFFF","#f9a8d4","#374151"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── FORMAL ──
  {
    _id: "mock_029",
    name: "Men's 3-Piece Formal Suit",
    brand: "Raymond",
    price: 8999, mrp: 14999, discount: 40,
    category: "Men", subCategory: "Formal", gender: "Men",
    description: "Impeccably tailored 3-piece suit in premium Italian wool. Includes jacket, trousers, and waistcoat.",
    image: p(653429), image2: p(9210389),
    rating: 4.8, reviewCount: 432,
    sizes: ["38","40","42","44","46","48"], colors: ["#1a1a1a","#1e3a5f","#374151"],
    inStock: true, isTrending: true, freeShipping: true,
  },

  // ── KIDS ──
  {
    _id: "mock_030",
    name: "Kids Superhero Graphic Tee",
    brand: "FirstCry",
    price: 399, mrp: 799, discount: 50,
    category: "Kids", subCategory: "T-Shirts", gender: "Kids",
    description: "Bright superhero graphic tee that every kid will love. 100% soft cotton, machine washable.",
    image: p(2839070), image2: p(16878046),
    rating: 4.7, reviewCount: 3456,
    sizes: ["2Y","3Y","4Y","5Y","6Y","8Y","10Y"], colors: ["#dc2626","#1e3a5f","#059669"],
    inStock: true, isTrending: true, freeShipping: true,
  },
];

export default mockProducts;
